/// Synthetic Gujarat Governance Data (SyntheticGujaratData)
/// Provides realistic Gujarat development needs, MPLADS capital works, PFMS escrow ledgers,
/// and stakeholder demo profiles for local offline repository initialization and hackathon evaluations.
class SyntheticGujaratData {
  static final List<Map<String, dynamic>> fallbackNeeds = [
    {
      'needId': 'ND-2026-SRT-0104',
      'creatorUserId': 'USR-CTZ-7721',
      'titleEnglish': 'Severe Potholes on Surat-Gaurav Path',
      'titleVernacular': 'સુરત ગૌરવ પથ પર ગંભીર ખાડાઓ',
      'departmentId': 'DEPT_ROADS_HIGHWAYS',
      'priorityScore': 94.5,
      'status': 'VERIFIED_AI',
      'severityClass': 'CRITICAL',
      'upvoteCount': 235,
      'commentCount': 18,
      'locationId': 'WRD-GUJ-SRT-0014',
      'ancestries': ['IND', 'STATE-GUJ', 'DIST-SRT', 'CORP-SMC', 'ZONE-WEST', 'WRD-GUJ-SRT-0014'],
      'geospatial': {'lat': 21.1959, 'lng': 72.7933, 'geohash': 'te7uu1q'},
      'aiIntelligence': {
        'confidence': 98.4,
        'duplicateScore': 12.0,
        'estimatedCostINR': 5000000.0,
        'estimatedBeneficiaries': 14200,
        'impactScore': 88.5,
      },
      'corroboratingWitnessIds': ['USR-CTZ-101', 'USR-CTZ-102', 'USR-CTZ-103', 'USR-CTZ-104'],
      'supporterIds': ['USR-CTZ-101', 'USR-CTZ-102', 'USR-CTZ-103', 'USR-CTZ-104'],
      'comments': [
        {
          'id': 'cmt-1',
          'authorName': 'Jignesh Shah',
          'authorRole': 'Citizen Witness',
          'content': 'Potholes causing severe traffic jams near school every morning. Please prioritize!',
          'timestamp': '2026-07-04T09:15:00Z',
          'likes': 14,
        },
        {
          'id': 'cmt-2',
          'authorName': 'Roads Dept Officer',
          'authorRole': 'Executive Engineer',
          'content': 'AI verification completed. Tender work order draft is being prepared for emergency repair.',
          'timestamp': '2026-07-04T14:30:00Z',
          'likes': 28,
        },
      ],
      'timeline': {
        'reportedDate': '2026-07-01T08:30:00Z',
        'verifiedDate': '2026-07-01T08:30:15Z',
        'approvedDate': '2026-07-02T11:00:00Z',
        'tenderDate': null,
        'constructionDate': null,
        'completedDate': null,
      },
      'linkedProjectId': 'PRJ-2026-SRT-8841',
    },
    {
      'needId': 'ND-2026-SRT-0105',
      'creatorUserId': 'USR-CTZ-8812',
      'titleEnglish': 'Low Water Pressure in Adajan Sector 4',
      'titleVernacular': 'અડાજણ સેક્ટર 4 માં પાણીનું ઓછું દબાણ',
      'departmentId': 'DEPT_WATER_RESOURCES',
      'priorityScore': 82.0,
      'status': 'ROUTED_TO_OFFICER',
      'severityClass': 'HIGH',
      'upvoteCount': 128,
      'commentCount': 9,
      'locationId': 'WRD-GUJ-SRT-0014',
      'ancestries': ['IND', 'STATE-GUJ', 'DIST-SRT', 'CORP-SMC', 'ZONE-WEST', 'WRD-GUJ-SRT-0014'],
      'geospatial': {'lat': 21.1980, 'lng': 72.7910, 'geohash': 'te7uu1s'},
      'aiIntelligence': {
        'confidence': 94.2,
        'duplicateScore': 5.0,
        'estimatedCostINR': 2500000.0,
        'estimatedBeneficiaries': 8500,
        'impactScore': 76.0,
      },
      'corroboratingWitnessIds': ['USR-CTZ-201', 'USR-CTZ-202'],
      'supporterIds': ['USR-CTZ-201', 'USR-CTZ-202'],
      'comments': [
        {
          'id': 'cmt-10',
          'authorName': 'Meena Ben Desai',
          'authorRole': 'Local Resident',
          'content': 'Water pressure is very low on 2nd and 3rd floors since last week.',
          'timestamp': '2026-07-03T07:45:00Z',
          'likes': 9,
        },
      ],
      'timeline': {
        'reportedDate': '2026-07-02T10:15:00Z',
        'verifiedDate': '2026-07-02T10:15:20Z',
        'approvedDate': null,
        'tenderDate': null,
        'constructionDate': null,
        'completedDate': null,
      },
      'linkedProjectId': null,
    }
  ];

  static final List<Map<String, dynamic>> fallbackProjects = [
    {
      'projectId': 'PRJ-2026-SRT-8841',
      'projectName': '4-Lane Elevated Flyover at Adajan Patia',
      'departmentId': 'DEPT_ROADS_HIGHWAYS',
      'linkedNeedIds': ['ND-2026-SRT-0104'],
      'ownership': {
        'sanctionedByAuthorityId': 'USR-MP-CR-PATIL',
        'sanctioningRole': 'MP_CONSTITUENCY',
        'responsibleOfficerId': 'OFF-GUJ-ROADS-009',
        'assignedContractorId': 'CONT-LNT-001',
        'contractorGstin': '24AAACL0140P1Z1',
        'contractorName': 'L&T Infrastructure Ltd',
      },
      'financials': {
        'fundingSource': 'MPLADS_CONSTITUENCY_FUND',
        'sanctionedBudgetINR': 15000000.0,
        'disbursedAmountINR': 6000000.0,
        'escrowAccountHash': 'PFMS-ESC-2026-8891',
      },
      'timeline': {
        'reportedDate': '2026-06-10T00:00:00Z',
        'verifiedDate': '2026-06-11T00:00:00Z',
        'approvedDate': '2026-06-15T00:00:00Z',
        'tenderDate': '2026-06-20T00:00:00Z',
        'constructionDate': '2026-06-25T00:00:00Z',
        'completedDate': null,
      },
      'progressPercentage': 40,
      'currentStatus': 'IN_EXECUTION',
      'milestones': [
        {'stage': 'Tranche 1 (Sanction & Mobilization)', 'status': 'RELEASED', 'amountINR': 6000000.0},
        {'stage': 'Tranche 2 (50% Structural Health Verification)', 'status': 'PENDING_AUDIT_RELEASE', 'amountINR': 6000000.0},
        {'stage': 'Tranche 3 (Defect Liability & Final Completion)', 'status': 'ESCROW_LOCKED', 'amountINR': 3000000.0},
      ],
    },
    {
      'projectId': 'PRJ-2026-SRT-9022',
      'projectName': '24x7 Surface Water Treatment Plant (Rander)',
      'departmentId': 'DEPT_WATER_RESOURCES',
      'linkedNeedIds': ['ND-2026-SRT-0099'],
      'ownership': {
        'sanctionedByAuthorityId': 'USR-ADMIN-HQ-001',
        'sanctioningRole': 'STATE_ADMIN',
        'responsibleOfficerId': 'OFF-GUJ-WATER-014',
        'assignedContractorId': 'CONT-TATA-004',
        'contractorGstin': '24AAACT8888P1Z9',
        'contractorName': 'Tata Projects & Sensors',
      },
      'financials': {
        'fundingSource': 'STATE_CAPITAL_EXPENDITURE',
        'sanctionedBudgetINR': 28000000.0,
        'disbursedAmountINR': 20000000.0,
        'escrowAccountHash': 'PFMS-ESC-2026-9044',
      },
      'timeline': {
        'reportedDate': '2026-05-01T00:00:00Z',
        'verifiedDate': '2026-05-05T00:00:00Z',
        'approvedDate': '2026-05-10T00:00:00Z',
        'tenderDate': '2026-05-20T00:00:00Z',
        'constructionDate': '2026-06-01T00:00:00Z',
        'completedDate': '2026-07-01T00:00:00Z',
      },
      'progressPercentage': 75,
      'currentStatus': 'MILESTONE_2_VERIFIED',
      'milestones': [
        {'stage': 'Tranche 1 (Foundation & Piping)', 'status': 'RELEASED', 'amountINR': 10000000.0},
        {'stage': 'Tranche 2 (Pump & Sensor Integration)', 'status': 'RELEASED', 'amountINR': 10000000.0},
        {'stage': 'Tranche 3 (Operational Handover)', 'status': 'PENDING_AUDIT_RELEASE', 'amountINR': 8000000.0},
      ],
    }
  ];

  static final List<Map<String, dynamic>> fallbackLedger = [
    {
      'projectId': 'PRJ-2026-SRT-8841',
      'projectName': 'Gaurav Path Express Flyover Construction',
      'contractor': 'L&T Infrastructure Ltd',
      'escrowId': 'PFMS-ESC-2026-8891',
      'sanctionedLakhs': 90.0,
      'disbursedLakhs': 18.0,
      'status': 'IN_EXECUTION',
      'tranche1': 'RELEASED',
      'tranche2': 'PENDING_AUDIT_RELEASE',
      'tranche3': 'ESCROW_LOCKED',
    },
    {
      'projectId': 'PRJ-2026-SRT-9022',
      'projectName': 'Adajan Ward 14 Smart Water Metering Grid',
      'contractor': 'Tata Projects & Sensors',
      'escrowId': 'PFMS-ESC-2026-9044',
      'sanctionedLakhs': 45.0,
      'disbursedLakhs': 45.0,
      'status': 'COMPLETED_RELEASED',
      'tranche1': 'RELEASED',
      'tranche2': 'RELEASED',
      'tranche3': 'RELEASED',
    },
    {
      'projectId': 'PRJ-2026-SRT-7721',
      'projectName': 'Surat West Stormwater Drainage Resilience Grid',
      'contractor': 'Gujarat Civil Works Corp',
      'escrowId': 'PFMS-ESC-2026-7721',
      'sanctionedLakhs': 60.0,
      'disbursedLakhs': 12.0,
      'status': 'IN_EXECUTION',
      'tranche1': 'RELEASED',
      'tranche2': 'PENDING_AUDIT_RELEASE',
      'tranche3': 'ESCROW_LOCKED',
    },
  ];

  static const double defaultMpladsFundINR = 50000000.0; // ₹5.00 Crore
}
